"""
Django settings for linux_bro project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from decouple import config, Csv

# JWT compatibility fix for django-allauth - MUST be first, before ANY other imports
# This ensures jwt.PyJWTError is always available (the main issue with django-allauth)
def _patch_jwt_aggressively():
    """Aggressively patch jwt module to ensure PyJWTError is available"""
    try:
        # Force import and patch
        import importlib
        jwt_module = importlib.import_module('jwt')
        
        # Import PyJWTError - this is what django-allauth needs
        from jwt.exceptions import PyJWTError
        
        # ALWAYS set PyJWTError attribute (this is the critical fix)
        jwt_module.PyJWTError = PyJWTError
        
        # Force into sys.modules
        sys.modules['jwt'] = jwt_module
        
        # Also patch any existing references in sys.modules
        for key in list(sys.modules.keys()):
            if key == 'jwt':
                try:
                    mod = sys.modules[key]
                    if hasattr(mod, '__name__') and mod.__name__ == 'jwt':
                        mod.PyJWTError = PyJWTError
                except (AttributeError, TypeError):
                    pass
        
        return True
    except (ImportError, AttributeError):
        # Silently fail if jwt is not available
        return False

# Patch immediately
_patch_jwt_aggressively()

# Also set up a meta path finder to patch on every import
class JWTPatcher:
    """Meta path finder that patches jwt on import"""
    def find_spec(self, name, path, target=None):
        if name == 'jwt':
            # Patch jwt when it's being imported
            _patch_jwt_aggressively()
        return None

# Add to meta path (but only once)
if not any(isinstance(finder, JWTPatcher) for finder in sys.meta_path):
    sys.meta_path.insert(0, JWTPatcher())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Security settings - Disable HTTPS redirects for HTTP-only deployment
SECURE_SSL_REDIRECT = False  # Don't redirect HTTP to HTTPS
SESSION_COOKIE_SECURE = False  # Allow cookies over HTTP
CSRF_COOKIE_SECURE = False  # Allow CSRF cookies over HTTP
SECURE_PROXY_SSL_HEADER = None  # Don't trust proxy headers for SSL

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    # Import home first to apply JWT compatibility patch before allauth
    'home',
    'ckeditor',
    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.twitter_oauth2',
    # Other installed apps
    'accounts',
    'blog',
    'contact'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'linux_bro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.google_client_id',
            ],
        },
    },
]

# Allauth configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = config('SITE_ID', default=1, cast=int)

# Allauth settings
# Updated to use new django-allauth settings format
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Set to 'mandatory' if you want email verification
ACCOUNT_ADAPTER = 'home.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'home.adapters.SocialAccountAdapter'
LOGIN_REDIRECT_URL = '/'  # Redirect after login
ACCOUNT_LOGOUT_REDIRECT_URL = '/'  # Redirect after logout
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'  # Use HTTP (change to 'https' when SSL is configured)

# Skip intermediate confirmation page for social logins
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_LOGIN_ON_GET = True  # This skips the intermediate page!

# Google Client ID for JavaScript SDK
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')

# Social account providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    },
    'github': {
        'SCOPE': [
            'user:email',
        ],
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    },
    'apple': {
        'APP': {
            'client_id': config('APPLE_CLIENT_ID', default='your.apple.client.id'),
            'secret': config('APPLE_SECRET', default='your.apple.secret'),
            'key': config('APPLE_KEY', default='your.apple.key'),
        }
    },
    # Twitter OAuth2 is configured via database (SocialApp model)
    # Remove from settings to avoid conflicts with database apps
    # 'twitter_oauth2': {
    #     'APP': {
    #         'client_id': config('TWITTER_CONSUMER_KEY', default='your.twitter.consumer.key'),
    #         'secret': config('TWITTER_CONSUMER_SECRET', default='your.twitter.consumer.secret'),
    #     }
    # }
}

WSGI_APPLICATION = 'linux_bro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
   os.path.join(BASE_DIR, 'static')
]
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files settings
MEDIA_URL = 'media/'
# For production, use absolute path matching nginx configuration
if DEBUG:
    MEDIA_URL = 'media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    # AWS S3 settings for media storage
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default=None)

    # Optional custom domain (e.g., CDN or custom CNAME). If not provided, fall back to standard S3 domain.
    _default_s3_domain = (
        f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
        if not AWS_S3_REGION_NAME
        else f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
    )
    AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default=_default_s3_domain)

    # Recommended S3 settings for public media
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False

    # Use S3 for default file storage (media)
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    # Media URL served from S3
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CKEditor Configuration
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['Image', 'Table', 'HorizontalRule'],
            ['CodeSnippet'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'Source'],
        ],
        'height': 400,
        'width': '100%',
        'extraPlugins': ','.join([
            'codesnippet',
        ]),
        'codeSnippet_theme': 'github',  # Available themes: default, github, googlecode, xcode, etc.
        'codeSnippet_codeClass': 'hljs',  # CSS class for code elements
        'codeSnippet_languages': {
            'bash': 'Bash',
            'c': 'C',
            'cpp': 'C++',
            'csharp': 'C#',
            'css': 'CSS',
            'django': 'Django',
            'html': 'HTML',
            'java': 'Java',
            'javascript': 'JavaScript',
            'json': 'JSON',
            'php': 'PHP',
            'python': 'Python',
            'ruby': 'Ruby',
            'sql': 'SQL',
            'xml': 'XML',
            'yaml': 'YAML',
        },
    },
}
