from django.urls import path
from .views import (
    LandingPageView,
    BlogPageView,
    AboutUsView,
    ContactView,
    ContactFormView,
    AuthorProfileView,
    MyProfileView,
    FollowAuthorView,
    SaveStoryView,
    LikeStoryView,
    CommentAjaxView,
    DeleteCommentView,
    LikeCommentView,
    LoginView,
    CustomLogoutView,
    AjaxSignupView,
    AuthorEditView,
    FilterSearchResultsView,
    TeamMemberListView,
    TeamMemberCreateView,
    TeamMemberUpdateView,
    TeamMemberDeleteView,
)

urlpatterns = [
    path("", LandingPageView.as_view(), name="home"),
    path("blog/<uuid:uuid>", BlogPageView.as_view(), name="blog"),
    path("our-story/", AboutUsView.as_view(), name="our_story"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("contact/submit/", ContactFormView.as_view(), name="contact_submit"),
    path("author/<uuid:uuid>", AuthorProfileView.as_view(), name="author_profile"),
    path("profile/", MyProfileView.as_view(), name="my_profile"),
    path("results/", FilterSearchResultsView.as_view(), name="filter-search-results"),
    path("results/<slug:slug>/", FilterSearchResultsView.as_view(), name="filter-search-results-slug"),
    path("follow-author/", FollowAuthorView.as_view(), name="follow-author"),
    path("save-story/", SaveStoryView.as_view(), name="save-story"),
    path("like/", LikeStoryView.as_view(), name="like_story"),
    path("comments/", CommentAjaxView.as_view(), name="comments_ajax"),
    path("delete/comment/", DeleteCommentView.as_view(), name="delete_comment"),
    path("like/comment/", LikeCommentView.as_view(), name="like_comment"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("ajax-signup/", AjaxSignupView.as_view(), name="ajax_signup"),
    path("author/edit/", AuthorEditView.as_view(), name="author_edit"),
    path("team-members/", TeamMemberListView.as_view(), name="team_member_list"),
    path("team-members/create/", TeamMemberCreateView.as_view(), name="team_member_create"),
    path("team-members/update/", TeamMemberUpdateView.as_view(), name="team_member_update"),
    path("team-members/delete/", TeamMemberDeleteView.as_view(), name="team_member_delete"),
]
