# Generated by Django 5.0.7 on 2024-10-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_story_views_storyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.response'),
        ),
    ]
