# Generated by Django 5.0.7 on 2025-10-22 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_response_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional banner image for featured display.",
                null=True,
                upload_to="media/blog_banners/",
                verbose_name="Banner Image",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="is_banner",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this story should appear as a featured banner.",
                verbose_name="Display as Banner",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="home.category",
            ),
        ),
    ]
