# Generated by Django 5.2.3 on 2025-11-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_add_comment_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="team_members/"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order for display"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "created_date"],
            },
        ),
    ]
