# Generated by Django 5.2.3 on 2025-11-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="Linux Bro", max_length=200)),
                (
                    "address_line1",
                    models.CharField(
                        default="Empowering Tech Enthusiasts Worldwide", max_length=200
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("phone1", models.CharField(default="+1 234 567 890", max_length=20)),
                ("phone2", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "email",
                    models.EmailField(default="contact@linuxbro.com", max_length=254),
                ),
                ("map_latitude", models.CharField(default="48.8583701", max_length=20)),
                ("map_longitude", models.CharField(default="2.2922873", max_length=20)),
                ("map_zoom", models.IntegerField(default=17)),
            ],
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Information",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
