# Generated by Django 5.2.3 on 2025-11-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_contactinfo_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creative_title",
                    models.CharField(default="We're Creative", max_length=200),
                ),
                (
                    "creative_lead",
                    models.TextField(help_text="Lead paragraph for Creative section"),
                ),
                ("creative_paragraph1", models.TextField(help_text="First paragraph")),
                ("creative_paragraph2", models.TextField(help_text="Second paragraph")),
                ("creative_paragraph3", models.TextField(help_text="Third paragraph")),
                ("creative_paragraph4", models.TextField(help_text="Fourth paragraph")),
                (
                    "friendly_title",
                    models.CharField(default="We're Friendly", max_length=200),
                ),
                (
                    "friendly_lead",
                    models.TextField(help_text="Lead paragraph for Friendly section"),
                ),
                ("friendly_paragraph1", models.TextField(help_text="First paragraph")),
                ("friendly_paragraph2", models.TextField(help_text="Second paragraph")),
                ("friendly_paragraph3", models.TextField(help_text="Third paragraph")),
                ("friendly_paragraph4", models.TextField(help_text="Fourth paragraph")),
                (
                    "video_title_line1",
                    models.CharField(default="Watch our", max_length=100),
                ),
                (
                    "video_title_line2",
                    models.CharField(default="video", max_length=100),
                ),
                (
                    "video_description",
                    models.TextField(help_text="Description text for video section"),
                ),
                (
                    "video_url",
                    models.CharField(
                        default="M06YHZ9YUdI",
                        help_text="YouTube video ID",
                        max_length=200,
                    ),
                ),
                (
                    "promote_title",
                    models.CharField(default="Promote Your Company", max_length=200),
                ),
                (
                    "promote_lead",
                    models.CharField(
                        default="Creating your own slogan here", max_length=200
                    ),
                ),
                (
                    "promote_description",
                    models.TextField(help_text="Description for Promote section"),
                ),
                (
                    "promote_button_text",
                    models.CharField(default="Start Your Story", max_length=100),
                ),
                (
                    "promote_button_link",
                    models.CharField(
                        default="/", help_text="Link URL for button", max_length=200
                    ),
                ),
                (
                    "project_title",
                    models.CharField(default="Make a Project With Us", max_length=200),
                ),
                (
                    "project_subtitle",
                    models.CharField(
                        default="Our Team is always ready to help you", max_length=200
                    ),
                ),
                (
                    "project_description",
                    models.TextField(help_text="Description for Project section"),
                ),
                (
                    "project_button_text",
                    models.CharField(default="Get In Touch", max_length=100),
                ),
                (
                    "project_button_link",
                    models.CharField(
                        default="/contact/",
                        help_text="Link URL for button",
                        max_length=200,
                    ),
                ),
                (
                    "team_title",
                    models.CharField(default="Meet The Team", max_length=200),
                ),
                (
                    "team_subtitle",
                    models.CharField(default="Meet the Linux Bro team", max_length=200),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Us Content",
                "verbose_name_plural": "About Us Content",
            },
        ),
        migrations.CreateModel(
            name="FooterContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission_title",
                    models.CharField(default="Our Mission", max_length=200),
                ),
                ("mission_text", models.TextField(help_text="Mission statement text")),
                ("facebook_url", models.URLField(blank=True, default="#")),
                ("twitter_url", models.URLField(blank=True, default="#")),
                ("linkedin_url", models.URLField(blank=True, default="#")),
                ("github_url", models.URLField(blank=True, default="#")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Footer Content",
                "verbose_name_plural": "Footer Content",
            },
        ),
    ]
