# Generated by Django 5.2.3 on 2025-11-04 06:28

from django.db import migrations


def populate_about_us_content(apps, schema_editor):
    """Populate AboutUsContent with original template content"""
    AboutUsContent = apps.get_model('home', 'AboutUsContent')
    
    # Only create if it doesn't exist
    if not AboutUsContent.objects.exists():
        AboutUsContent.objects.create(
            # We're Creative Section
            creative_title="We're Creative",
            creative_lead="We are a full-service digital content platform, and we're also one of the top tech storytelling platforms because we draw to projects that challenge our creative work.",
            creative_paragraph1="At Linux Bro, we believe in the power of storytelling and technology. Our platform brings together the best of both worlds - creative content that challenges conventions and technical expertise that makes it all possible.",
            creative_paragraph2="We're passionate about sharing knowledge, inspiring others, and building a community of tech enthusiasts who love to learn and grow together.",
            creative_paragraph3="Every story we publish is crafted with care, ensuring that our readers get valuable insights, practical knowledge, and inspiration to take their tech journey to the next level.",
            creative_paragraph4="",
            
            # We're Friendly Section
            friendly_title="We're Friendly",
            friendly_lead="We're proud of our work to accomplish and much of the credit goes to our amazing and unique culture which helps us to come together to overcome all of our challenging times.",
            friendly_paragraph1="Our community is built on friendship, respect, and a shared passion for technology. We believe that the best learning happens when people feel welcome and supported.",
            friendly_paragraph2="Whether you're a beginner just starting your tech journey or an experienced developer looking to share your knowledge, you'll find a friendly community here at Linux Bro.",
            friendly_paragraph3="We're here to help, inspire, and grow together. Join us and become part of a community that values creativity, friendship, and continuous learning.",
            friendly_paragraph4="",
            
            # Watch Our Video Section
            video_title_line1="Watch our",
            video_title_line2="video",
            video_description="Discover the story behind Linux Bro\nand our mission to empower\ntech enthusiasts worldwide",
            video_url="M06YHZ9YUdI",
            
            # Promote Your Company Section
            promote_title="Promote Your Company",
            promote_lead="Creating your own slogan here",
            promote_description="Share your tech story with the world. Linux Bro provides a platform for companies and individuals to showcase their innovations, share their expertise, and connect with a global community of tech enthusiasts.",
            promote_button_text="Start Your Story",
            promote_button_link="/",
            
            # Make a Project With Us Section
            project_title="Make a Project With Us",
            project_subtitle="Our Team is always ready to help you",
            project_description="Have an idea for a story? Want to collaborate on a project? Our team is here to help you bring your vision to life. Let's create something amazing together.",
            project_button_text="Get In Touch",
            project_button_link="/contact/",
            
            # Meet The Team Section
            team_title="Meet The Team",
            team_subtitle="Meet the Linux Bro team",
        )


def populate_footer_content(apps, schema_editor):
    """Populate FooterContent with original template content"""
    FooterContent = apps.get_model('home', 'FooterContent')
    
    # Only create if it doesn't exist
    if not FooterContent.objects.exists():
        FooterContent.objects.create(
            mission_title="Our Mission",
            mission_text="At Linux Bro, we are passionate about empowering tech enthusiasts through quality tutorials and educational content. Our mission is to make technology accessible to everyone, regardless of their skill level. We believe in the power of knowledge sharing and strive to create a friendly community where learners can grow, innovate, and succeed together.",
            facebook_url="#",
            twitter_url="#",
            linkedin_url="#",
            github_url="#",
        )


def reverse_populate(apps, schema_editor):
    """Reverse migration - delete all content"""
    AboutUsContent = apps.get_model('home', 'AboutUsContent')
    FooterContent = apps.get_model('home', 'FooterContent')
    
    AboutUsContent.objects.all().delete()
    FooterContent.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_aboutuscontent_footercontent"),
    ]

    operations = [
        migrations.RunPython(populate_about_us_content, reverse_populate),
        migrations.RunPython(populate_footer_content, reverse_populate),
    ]
