# Generated by Django 5.2.3 on 2025-11-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_auto_20251104_0628"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/blog_images/"
            ),
        ),
    ]
