# Generated by Django 5.2.3 on 2025-11-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_make_cover_image_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentblock",
            name="video_url",
            field=models.CharField(
                blank=True,
                help_text="YouTube video ID (e.g., 'M06YHZ9YUdI') or full URL",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("paragraph", "Paragraph"),
                    ("image", "Image"),
                    ("blockquote", "Block Quote"),
                    ("youtube", "YouTube Video"),
                ],
                max_length=20,
            ),
        ),
    ]
