# Generated by Django 5.2.3 on 2025-11-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_add_youtube_content_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for this ad space (e.g., 'Sidebar Top Ad')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("top", "Top (Above Popular Posts)"),
                            ("middle", "Middle (Between Popular Posts and Tags)"),
                            ("bottom", "Bottom (Below Categories)"),
                        ],
                        help_text="Where this ad should appear in the sidebar",
                        max_length=20,
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("adsense", "Google AdSense"),
                            ("meta", "Meta Ads (Facebook)"),
                            ("custom", "Custom HTML/JavaScript"),
                        ],
                        default="adsense",
                        help_text="Type of ad (AdSense, Meta Ads, or Custom)",
                        max_length=20,
                    ),
                ),
                (
                    "ad_code",
                    models.TextField(
                        help_text="Paste your AdSense code, Meta Ads code, or custom HTML/JavaScript here"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active ads will be displayed"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ad Space",
                "verbose_name_plural": "Ad Spaces",
                "ordering": ["position", "name"],
            },
        ),
    ]
