# Generated by Django 5.2.8 on 2025-11-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_adspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="SEO meta description (150-160 characters recommended). If left blank, will use subtitle or first content block.",
                max_length=160,
                null=True,
                verbose_name="Meta Description",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords for SEO. If left blank, will use tags and category.",
                max_length=255,
                null=True,
                verbose_name="Meta Keywords",
            ),
        ),
    ]
