# Generated by Django 5.2.8 on 2025-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_story_meta_description_story_meta_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentblock",
            name="code_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Plain Text"),
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("java", "Java"),
                    ("cpp", "C++"),
                    ("c", "C"),
                    ("html", "HTML"),
                    ("css", "CSS"),
                    ("sql", "SQL"),
                    ("bash", "Bash/Shell"),
                    ("json", "JSON"),
                    ("xml", "XML"),
                    ("yaml", "YAML"),
                    ("markdown", "Markdown"),
                    ("php", "PHP"),
                    ("ruby", "Ruby"),
                    ("go", "Go"),
                    ("rust", "Rust"),
                    ("swift", "Swift"),
                    ("kotlin", "Kotlin"),
                    ("typescript", "TypeScript"),
                    ("dart", "Dart"),
                ],
                default="",
                help_text="Programming language for syntax highlighting (only used for code blocks)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("paragraph", "Paragraph"),
                    ("image", "Image"),
                    ("blockquote", "Block Quote"),
                    ("youtube", "YouTube Video"),
                    ("code", "Code Block"),
                ],
                max_length=20,
            ),
        ),
    ]
