# Generated by Django 5.2.8 on 2025-11-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_contentblock_code_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("paragraph", "Paragraph"),
                    ("subheading", "Subheading"),
                    ("image", "Image"),
                    ("blockquote", "Block Quote"),
                    ("youtube", "YouTube Video"),
                    ("code", "Code Block"),
                ],
                max_length=20,
            ),
        ),
    ]
